### PR TITLE
Get will not crash on accepting null

### PR DESCRIPTION
**Pull request by gja**

### CODE REVIEW

**Comment by javifraile** [comment]
This PR is necessary. I got a crash because instead of undefined, I received a null from an API with the code:
`dotProp.get(settings, 'value')`

**Comment by gavinsharp** [comment]
#23 is essentially the same fix, but a bit more complete (also covers delete and adds comments).

**Comment by hilleer** [comment]
Hi @gja,

Thanks for your contribution. 

This should be fixed with those changes: https://github.com/debitoor/dot-prop-immutable/pull/23 which is in included in version `1.6.0`.

**Comment by hilleer** [comment]
Should fix https://github.com/debitoor/dot-prop-immutable/issues/34.

**Pull request closed without merging**
